'use client'

import React from 'react'
import Container from '@/components/ui/Container'
import ScrollReveal from '@/components/layout/ScrollReveal'

export default function IdentityWriting() {
  return (
    <section id="identity" className="py-24 md:py-32">
      <Container>
        <ScrollReveal>
          <div className="mb-16 max-w-3xl">
            <p className="font-mono text-xs tracking-[2px] uppercase text-accent-500 mb-4">
              BEYOND PERSONALIZATION
            </p>
            <h2 className="text-[clamp(32px,4vw,48px)] font-bold tracking-tight leading-[1.15]">
              We don&apos;t personalize the message. We personalize the sender.
            </h2>
          </div>
        </ScrollReveal>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">
          {/* Left: Text */}
          <ScrollReveal>
            <div className="space-y-5 max-w-[520px]">
              <p className="text-sm text-primary-400 leading-[1.75]">
                Most outreach tools personalize for the recipient, they insert the
                prospect&apos;s name, mention their company, maybe reference a recent LinkedIn
                post. The message is still obviously templated. The &quot;uncanny valley&quot; of
                AI text triggers an immediate delete.
              </p>
              <p className="text-sm text-primary-400 leading-[1.75]">
                We take the opposite approach. We study how you actually write, your sentence
                length, your vocabulary choices, your punctuation habits, your sign-offs, and
                calibrate the system to produce messages indistinguishable from your natural
                writing.
              </p>
              <p className="text-sm text-primary-400 leading-[1.75]">
                The result: your prospects respond to what feels like a personal email from a
                peer, not a campaign blast from a tool. This isn&apos;t cosmetic. Reply rates for
                identity-matched outreach consistently outperform template-based campaigns by
                multiples, not percentages.
              </p>
            </div>
          </ScrollReveal>

          {/* Right: Email comparison */}
          <ScrollReveal delay={120}>
            <div className="space-y-4">
              {/* Template-based example */}
              <div className="border border-primary-800/50 rounded-lg p-6 bg-primary-900/30">
                <p className="font-mono text-[11px] tracking-[1.5px] uppercase text-primary-600 mb-4">
                  TEMPLATE-BASED
                </p>
                <div className="font-mono text-[13px] text-primary-500 leading-[1.8] whitespace-pre-line">
                  {`Hi {{first_name}},

I noticed {{company_name}} is growing rapidly. We help companies like yours scale their outbound. Would you be open to a quick chat?

Best regards,
[Sales Rep]`}
                </div>
              </div>

              {/* Identity-matched example */}
              <div className="border border-accent-500/30 rounded-lg p-6 bg-primary-950">
                <p className="font-mono text-[11px] tracking-[1.5px] uppercase text-accent-500 mb-4">
                  IDENTITY-MATCHED
                </p>
                <div className="font-mono text-[13px] text-primary-300 leading-[1.8] whitespace-pre-line">
                  {`Hi Marcus,

Saw the VP Sales search go live last week \u2014 that usually means the outbound engine needs to catch up with the hiring plan. We\u2019ve been solving that exact timing problem for mid-market teams scaling past 50.

Worth a 15-min look?

- D`}
                </div>
              </div>

              <p className="text-[12px] text-primary-600">
                Both emails were generated by the same system. The difference is calibration.
              </p>
            </div>
          </ScrollReveal>
        </div>
      </Container>
    </section>
  )
}
